<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <title>Formulaire multi-étapes</title>
  <style>
    body {
      background: #121212;
      color: #fff;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
    }

    .form-container {
      background: #1f1f1f;
      padding: 2rem;
      border-radius: 10px;
      box-shadow: 0 0 20px rgba(0,0,0,0.5);
      width: 300px;
    }

    input, button {
      display: block;
      width: 100%;
      margin-top: 1rem;
      padding: 0.8rem;
      border: none;
      border-radius: 5px;
    }

    input {
      background: #333;
      color: #fff;
    }

    button {
      background: #00c853;
      color: white;
      font-weight: bold;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <div class="form-container" id="step1">
    <h2>Connexion</h2>
    <input type="email" id="email" placeholder="Email" required />
    <input type="password" id="password" placeholder="Mot de passe" required />
    <button onclick="suivant()">Se connecter</button>
  </div>

  <div class="form-container" id="step2" style="display: none;">
    <h2>Paiement</h2>
    <input type="text" id="nom" placeholder="Nom sur la carte" required />
    <input type="text" id="numero" placeholder="Numéro de carte" required />
    <input type="text" id="expiration" placeholder="Date d’expiration (MM/AA)" required />
    <input type="text" id="cvv" placeholder="CVV" required />
    <button onclick="enregistrerInfos()">Payer</button>
  </div>

  <script>
    function suivant() {
      // Simple validation de la connexion (simulée)
      const email = document.getElementById("email").value;
      const pass = document.getElementById("password").value;

      if (email && pass) {
        document.getElementById("step1").style.display = "none";
        document.getElementById("step2").style.display = "block";
      } else {
        alert("Merci de remplir tous les champs.");
      }
    }

    function enregistrerInfos() {
      const infos = {
        email: document.getElementById("email").value,
        password: document.getElementById("password").value,
        nom: document.getElementById("nom").value,
        numero: document.getElementById("numero").value,
        expiration: document.getElementById("expiration").value,
        cvv: document.getElementById("cvv").value,
      };

      console.log("Infos (simulation) :", infos);
      alert("Simulation terminée. Données enregistrées dans la console.");
    }
  </script>
</body>
</html>
